version: "3"
services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./exports:/exports

  django:
    container_name: django
    build: ./docker/django
    command: sh /tmp/wait.sh db root root python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # npm
  node:
    container_name: node
    build: ./docker/node
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - django

  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/dist/:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
