FORMAT: 1A
HOST: http://localhost/api

# Mima-community-bus api
- login api
- バス点検情報 api

<!-- include(01.data_structures.apib) -->
<!-- include(auth.apib) -->
<!-- include(bus_init.apib) -->
<!-- include(bus_inspection.apib) -->
<!-- include(bus_routes.apib) -->
<!-- include(bus_course.apib) -->
<!-- include(bus_course_info.apib) -->
<!-- include(bus_stops.apib) -->
<!-- include(bus_fare.apib) -->
<!-- include(bus_location.apib) -->
<!-- include(bus_boarding_number.apib) -->
<!-- include(bus_watch_over_boarding.apib) -->
<!-- include(card_idm.apib) -->
