from django.urls import path
from .views import *

urlpatterns = [
    # path('location/', GetBusLocationView.as_view()), <- 未実装
    # path('bus_record/', GetBusLocationView.as_view()), <- 未実装
    path("map/location/route/", CourseLocation.as_view()),
    path("drivers/", GetDriverList.as_view()),
    path("drivers/register/", DriverRegister.as_view()),
    path("drivers/delete/", DriverDelete.as_view()),
    path("drivers/update/", DriverUpdate.as_view()),
    path("buses/", BusesInfo.as_view()),
    path("buses/register/", BusesInfoRegister.as_view()),
    path("buses/update/", BusesInfoUpdate.as_view()),
    path("buses/delete/", BusesInfoDelete.as_view()),
    path("monitor/notification/", MonitoringNotice.as_view()),
    path("monitor/management/", MonitoringManage.as_view()),
    path("monitor/management/register/", MonitoringManageRegister.as_view()),
    path("monitor/management/update/", MonitoringManageUpdate.as_view()),
    path("monitor/management/delete/", MonitoringManageDelete.as_view()),
    path("monitor/history/", MonitoringHistory.as_view()),
    path("monitor/notification/", MonitoringNotice.as_view()),
    path("monitor/notification/update/", MonitoringNoticeUpdate.as_view()),
    path("user/", UserView.as_view()),
    path("user/register/", UserManagementRegister.as_view()),
    path("user/update/", UserManagementUpdate.as_view()),
    path("user/delete/", UserManagementDelete.as_view()),
    path("busStop/", AllBusStop.as_view()),
    path("route/", AllRoute.as_view()),
    path("route/register/", RouteRegistration.as_view()),
    path("route/update/", RouteEditation.as_view()),
    path("route/delete/", RouteDeletion.as_view()),
    path("busStop/register/", BusStopRegister.as_view()),
    path("busStop/update/", BusStopUpdate.as_view()),
    path("busStop/delete/", BusStopDelete.as_view()),
    path("course/", AllCourse.as_view()),
    path("course/register/", CourseRegistration.as_view()),
    path("course/update/", CourseEditation.as_view()),
    path("course/delete/", CourseDeletion.as_view()),
    path("report/day/", DailyReportList.as_view()),
    path("report/month/", MonthlyReportList.as_view()),
    path("report/day/download/", DailyReportDownload.as_view()),
    path("report/day/update/", DailyReportUpdate.as_view()),
    path("map/location/bus/", BusLocation.as_view()),
    path("notification/", GetNotifications.as_view()),
    path("notification/update/", UpdateNotifications.as_view()),
    path("bus/history/", GetBusRecord.as_view()),
    path("fare/", FareList.as_view()),
    path("fare/create/", FareUpdate.as_view()),
]
